<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Serilog.Sinks.MemorySink</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>x64;AnyCPU</Platforms>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkTooutputsPath>false</AppendTargetFrameworkTooutputsPath>
    <AppendRuntimeIdentifierTooutputsPath>false</AppendRuntimeIdentifierTooutputsPath>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" Version="10.0.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <Title>Serilog.Sinks.MemorySink</Title>
    <PackageId>Serilog.Sinks.MemorySink</PackageId>
    <Product>Serilog.Sinks.MemorySink</Product>
    <Description>A Serilog sink that store log events in memory. You can retrieve these logs and render them in your own log viewer.</Description>
    <Version>0.1.2</Version>
    <Authors>Fabio Baraldi</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) Elettrondata srl 2026</Copyright>
    <PackageTags>serilog;sinks;memory</PackageTags>
    <PackageProjectUrl>https://github.com/elettrondatasrl/serilog-sinks-memorysink</PackageProjectUrl>
    <RepositoryUrl>https://github.com/elettrondatasrl/serilog-sinks-memorysink</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>0.1.2</AssemblyVersion>
    <FileVersion>0.1.2</FileVersion>
    <!--<PackageIcon>icon.png</PackageIcon>-->
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Sinks\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

</Project>
